name: Deploy Astro to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  pages: write
  id-token: write
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Show Node & NPM versions
        run: |
          node -v
          npm -v

      # Sometimes npm ci fails on runners due to optional native deps.
      # Fall back to npm install so the job doesn't die early.
      - name: Install deps (try ci, fall back to install)
        run: |
          npm ci || npm install

      - name: Verify Astro
        run: npx astro --version

      - name: Build (verbose)
        env:
          NODE_OPTIONS: --max_old_space_size=3072
        run: npm run build -- --verbose

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
